development:
  adapter: postgresql
  database: notnice_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: notnice_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: postgresql
  pool: 5
  timeout: 5000
